USE SUCOS_VENDAS;

SELECT CURRENT_TIMESTAMP() AS RESULTADO;

SELECT CONCAT('O dia de hoje é : ', CURRENT_TIMESTAMP()) AS RESULTADO;

SELECT CONCAT('O dia de hoje é : ',
DATE_FORMAT(CURRENT_TIMESTAMP(),'%W, %d/%m/%y - %U')) AS RESULTADO;

SELECT CONCAT('O dia de hoje é : ', 
DATE_FORMAT(DATA_VENDA,'%Y')) as RESULTADO FROM NOTAS_FISCAIS
GROUP BY DATA_VENDA;

SELECT CONVERT(23.3, CHAR) AS RESULTADO;

SELECT SUBSTRING(CONVERT(23.3, CHAR),1,1) AS RESULTADO;

SELECT * FROM TABELA_DE_CLIENTES;
SELECT * FROM NOTAS_FISCAIS;
SELECT * FROM ITENS_NOTAS_FISCAIS;

SELECT TC.NOME, INF.PRECO, YEAR(NF.DATA_VENDA)
FROM TABELA_DE_CLIENTES TC
INNER JOIN NOTAS_FISCAIS NF ON TC.CPF = NF.CPF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY YEAR(DATA_VENDA), TC.NOME, INF.PRECO;

/* RESOLVENDO O EXERCÍCIO */
SELECT
CONCAT(
'O cliente ',
TC.NOME,
' faturou ',
CAST(ROUND(SUM(INF.QUANTIDADE * INF.PRECO),2) AS CHAR(20)),
' no ano de ', DATE_FORMAT(NF.DATA_VENDA, '%Y')
) AS FATURAMENTO_ANUAL
FROM TABELA_DE_CLIENTES TC
INNER JOIN NOTAS_FISCAIS NF ON TC.CPF = NF.CPF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2016
GROUP BY NF.DATA_VENDA, TC.NOME, INF.PRECO;