USE SUCOS_VENDAS;

SELECT CURDATE();

SELECT CURRENT_TIME();

SELECT CURRENT_TIMESTAMP();

SELECT YEAR(CURRENT_TIMESTAMP());

SELECT DAY(CURRENT_TIMESTAMP());

SELECT DAYNAME(CURRENT_TIMESTAMP());

SELECT MONTH(CURRENT_TIMESTAMP());

SELECT MONTHNAME(CURRENT_TIMESTAMP());

SELECT DATEDIFF(CURRENT_TIMESTAMP(), '1983-06-14') AS RESULTADO;

SELECT DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 5 DAY) AS RESULTADO;

SELECT CURRENT_TIMESTAMP() AS DIA_HOJE, DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 5 DAY) AS RESULTADO;

SELECT DISTINCT DATA_VENDA,
DAYNAME(DATA_VENDA) AS DIA, MONTHNAME(DATA_VENDA) AS MES, YEAR(DATA_VENDA) AS ANO
FROM NOTAS_FISCAIS
HAVING DAYNAME(DATA_VENDA) = 'Sunday';

SELECT * FROM TABELA_DE_CLIENTES;
SELECT NOME, IDADE, ROUND(DATEDIFF(CURRENT_TIMESTAMP(), DATA_DE_NASCIMENTO)/365,0) AS IDADE_ATUAL FROM TABELA_DE_CLIENTES;
SELECT NOME, TIMESTAMPDIFF(YEAR, DATA_DE_NASCIMENTO, CURDATE()) AS IDADE FROM TABELA_DE_CLIENTES;