CREATE DEFINER=`root`@`localhost` FUNCTION `f_numero_notas`(vData DATE) RETURNS int(11)
BEGIN
	DECLARE vNUMNOTAS INT;
    SELECT COUNT(*) INTO vNUMNOTAS FROM NOTAS_FISCAIS WHERE DATA_VENDA = vData;
RETURN vNUMNOTAS;
END