USE VENDAS_SUCOS;


/* Cria chave estrangeira caso não seja especificada na criação da tabela */
ALTER TABLE PRODUTOS ADD PRIMARY KEY (CODIGO);
ALTER TABLE ITENS_NOTAS ADD PRIMARY KEY (NUMERO, CODIGO);


/* CONSTRAINT significa restrições ou relacionamentos
Alterar tabela de vendas criando um relacionamento */
ALTER TABLE NOTAS ADD CONSTRAINT FK_CLIENTES
FOREIGN KEY (CPF)
REFERENCES VENDAS_SUCOS.CLIENTES (CPF);

ALTER TABLE NOTAS ADD CONSTRAINT FK_VENDEDORES
FOREIGN KEY (MATRICULA)
REFERENCES VENDEDORES(MATRICULA);

ALTER TABLE ITENS_NOTAS ADD CONSTRAINT FK_NOTAS
FOREIGN KEY (NUMERO)
REFERENCES NOTAS (NUMERO);

ALTER TABLE ITENS_NOTAS ADD CONSTRAINT FK_PRODUTOS
FOREIGN KEY (CODIGO)
REFERENCES PRODUTOS (CODIGO);