CREATE DEFINER=`root`@`localhost` PROCEDURE `tipos_de_dados`()
BEGIN
DECLARE v VARCHAR(5) DEFAULT 'TEXTO';
DECLARE i INTEGER DEFAULT 10;
DECLARE d DECIMAL(4,2) DEFAULT 56.12;
DECLARE dt DATE DEFAULT '2022-02-16';
SELECT v;
SELECT i;
SELECT d;
SELECT dt; 
END