USE SUCOS_VENDAS;

SELECT * FROM tabela_de_clientes;


SELECT NOME,
CASE
  WHEN YEAR(DATA_DE_NASCIMENTO) > 1995 THEN 'Crianças'
  WHEN YEAR(DATA_DE_NASCIMENTO) >= 1990 AND YEAR(DATA_DE_NASCIMENTO) <=1995 THEN 'Jovem'
  ELSE 'IDOSO'
END AS CLASSIFICACAO
FROM tabela_de_clientes
GROUP BY NOME,
CASE
  WHEN YEAR(DATA_DE_NASCIMENTO) > 1995 THEN 'Crianças'
  WHEN YEAR(DATA_DE_NASCIMENTO) >= 1990 AND YEAR(DATA_DE_NASCIMENTO) <=1995 THEN 'Jovem'
  ELSE 'IDOSO'
END
ORDER BY CLASSIFICACAO