-- MySQL Script generated by MySQL Workbench
-- Sun Feb 13 17:19:53 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sucos_vendas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sucos_vendas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sucos_vendas` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sucos_vendas` ;

-- -----------------------------------------------------
-- Table `sucos_vendas`.`tabela_de_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sucos_vendas`.`tabela_de_produtos` (
  `CODIGO_DO_PRODUTO` VARCHAR(10) NOT NULL,
  `NOME_DO_PRODUTO` VARCHAR(50) NULL DEFAULT NULL,
  `EMBALAGEM` VARCHAR(20) NULL DEFAULT NULL,
  `TAMANHO` VARCHAR(10) NULL DEFAULT NULL,
  `SABOR` VARCHAR(20) NULL DEFAULT NULL,
  `PRECO_DE_LISTA` FLOAT NOT NULL,
  PRIMARY KEY (`CODIGO_DO_PRODUTO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sucos_vendas`.`tabela_de_vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sucos_vendas`.`tabela_de_vendedores` (
  `MATRICULA` VARCHAR(5) NOT NULL,
  `NOME` VARCHAR(100) NULL DEFAULT NULL,
  `PERCENTUAL_COMISSAO` FLOAT NULL DEFAULT NULL,
  `DATA_ADMISSAO` DATE NULL DEFAULT NULL,
  `DE_FERIAS` BIT(1) NULL DEFAULT NULL,
  `BAIRRO` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`MATRICULA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sucos_vendas`.`tabela_de_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sucos_vendas`.`tabela_de_clientes` (
  `CPF` VARCHAR(11) NOT NULL,
  `NOME` VARCHAR(100) NULL DEFAULT NULL,
  `ENDERECO_1` VARCHAR(150) NULL DEFAULT NULL,
  `ENDERECO_2` VARCHAR(150) NULL DEFAULT NULL,
  `BAIRRO` VARCHAR(50) NULL DEFAULT NULL,
  `CIDADE` VARCHAR(50) NULL DEFAULT NULL,
  `ESTADO` VARCHAR(2) NULL DEFAULT NULL,
  `CEP` VARCHAR(8) NULL DEFAULT NULL,
  `DATA_DE_NASCIMENTO` DATE NULL DEFAULT NULL,
  `IDADE` SMALLINT(6) NULL DEFAULT NULL,
  `SEXO` VARCHAR(1) NULL DEFAULT NULL,
  `LIMITE_DE_CREDITO` FLOAT NULL DEFAULT NULL,
  `VOLUME_DE_COMPRA` FLOAT NULL DEFAULT NULL,
  `PRIMEIRA_COMPRA` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sucos_vendas`.`notas_fiscais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sucos_vendas`.`notas_fiscais` (
  `CPF` VARCHAR(11) NOT NULL,
  `MATRICULA` VARCHAR(5) NOT NULL,
  `DATA_VENDA` DATE NULL DEFAULT NULL,
  `NUMERO` INT(11) NOT NULL,
  `IMPOSTO` FLOAT NOT NULL,
  PRIMARY KEY (`NUMERO`),
  INDEX `MATRICULA` (`MATRICULA` ASC) VISIBLE,
  INDEX `CPF` (`CPF` ASC) VISIBLE,
  CONSTRAINT `notas_fiscais_ibfk_1`
    FOREIGN KEY (`MATRICULA`)
    REFERENCES `sucos_vendas`.`tabela_de_vendedores` (`MATRICULA`),
  CONSTRAINT `notas_fiscais_ibfk_2`
    FOREIGN KEY (`CPF`)
    REFERENCES `sucos_vendas`.`tabela_de_clientes` (`CPF`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sucos_vendas`.`itens_notas_fiscais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sucos_vendas`.`itens_notas_fiscais` (
  `NUMERO` INT(11) NOT NULL,
  `CODIGO_DO_PRODUTO` VARCHAR(10) NOT NULL,
  `QUANTIDADE` INT(11) NOT NULL,
  `PRECO` FLOAT NOT NULL,
  PRIMARY KEY (`NUMERO`, `CODIGO_DO_PRODUTO`),
  INDEX `CODIGO_DO_PRODUTO` (`CODIGO_DO_PRODUTO` ASC) VISIBLE,
  CONSTRAINT `itens_notas_fiscais_ibfk_1`
    FOREIGN KEY (`CODIGO_DO_PRODUTO`)
    REFERENCES `sucos_vendas`.`tabela_de_produtos` (`CODIGO_DO_PRODUTO`),
  CONSTRAINT `itens_notas_fiscais_ibfk_2`
    FOREIGN KEY (`NUMERO`)
    REFERENCES `sucos_vendas`.`notas_fiscais` (`NUMERO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `sucos_vendas` ;

-- -----------------------------------------------------
-- Placeholder table for view `sucos_vendas`.`vw_maiores_embalagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sucos_vendas`.`vw_maiores_embalagens` (`EMBALAGEM` INT, `MAIOR_PRECO` INT);

-- -----------------------------------------------------
-- View `sucos_vendas`.`vw_maiores_embalagens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sucos_vendas`.`vw_maiores_embalagens`;
USE `sucos_vendas`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `sucos_vendas`.`vw_maiores_embalagens` AS select `sucos_vendas`.`tabela_de_produtos`.`EMBALAGEM` AS `EMBALAGEM`,max(`sucos_vendas`.`tabela_de_produtos`.`PRECO_DE_LISTA`) AS `MAIOR_PRECO` from `sucos_vendas`.`tabela_de_produtos` group by `sucos_vendas`.`tabela_de_produtos`.`EMBALAGEM`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
