USE vendas_sucos;

CREATE TABLE PRODUTOS(
CODIGO VARCHAR(10) NOT NULL,
DESCRITOR VARCHAR(100) NULL,
SABOR VARCHAR(50) NULL,
TAMANHO VARCHAR(50) NULL,
EMBALAGEM VARCHAR(50) NULL,
PRECO_LISTA FLOAT NULL,
PRIMARY KEY(CODIGO)
);

CREATE TABLE VENDEDORES(
MATRICULA VARCHAR(5) NOT NULL,
NOME VARCHAR(100) NULL,
BAIRRO VARCHAR(50) NULL,
COMISSAO FLOAT NULL,
DATA_AIDMISSAO DATE NULL,
FERIAS BIT(1),
PRIMARY KEY(MATRICULA)
);

ALTER TABLE VENDEDORES RENAME COLUMN DATA_AIDMISSAO TO DATA_ADMISSAO;

CREATE TABLE NOTAS(
CPF VARCHAR(11) NOT NULL,
MATRICULA VARCHAR(5) NOT NULL,
DATA_VENDA DATE NULL,
NUMERO VARCHAR(11) NOT NULL,
IMPOSTO FLOAT NULL,
PRIMARY KEY(NUMERO)
);

CREATE TABLE CLIENTES(
CPF VARCHAR(11) NOT NULL,
NOME VARCHAR(100) NULL,
ENDERECO VARCHAR(150) NULL,
BAIRRO VARCHAR(50) NULL,
CIDADE VARCHAR(50) NULL,
ESTADO VARCHAR(50) NULL,
CEP VARCHAR(8) NULL,
DATA_NASCIMENTO DATE NULL,
IDADE INT NULL,
SEXO VARCHAR(1) NULL,
LIMITE_CREDITO FLOAT NULL,
VOLUME_COMPRA FLOAT NULL,
PRIMEIRA_COMPRA BIT(1),
PRIMARY KEY(CPF)
);

CREATE TABLE ITENS_NOTAS(
NUMERO VARCHAR(11) NOT NULL,
CODIGO VARCHAR(10) NOT NULL,
QUANTIDADE FLOAT NULL,
PRECO FLOAT NULL,
PRIMARY KEY(NUMERO, CODIGO)
);