
-- 8851.75 QUERY_COST
SELECT * FROM NOTAS_FISCAIS WHERE DATA_VENDA = '20170101';
EXPLAIN FORMAT=JSON SELECT * FROM NOTAS_FISCAIS WHERE DATA_VENDA = '20170101'; -- lembra de incluir \G no final, quando da linha de comando

-- Comando para criação do Índice, neste exemplo vamos nos base pela condição de filtro
ALTER TABLE NOTAS_FISCAIS ADD INDEX (DATA_VENDA);

-- 25.90 QUERY_COST
SELECT * FROM NOTAS_FISCAIS WHERE DATA_VENDA = '20170101';
EXPLAIN FORMAT=JSON SELECT * FROM NOTAS_FISCAIS WHERE DATA_VENDA = '20170101';

ALTER TABLE NOTAS_FISCAIS DROP INDEX DATA_VENDA;

-- 8815.75
EXPLAIN FORMAT=JSON SELECT * FROM NOTAS_FISCAIS WHERE DATA_VENDA = '20170101';