use sucos_vendas;

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS LIMITE_TOTAL
FROM TABELA_DE_CLIENTES GROUP BY ESTADO;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;

SELECT EMBALAGEM, COUNT(*) AS CONTADOR FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM;

SELECT ESTADO, BAIRRO, SUM(LIMITE_DE_CREDITO) AS LIMITE FROM TABELA_DE_CLIENTES
WHERE CIDADE = 'Rio de Janeiro'
GROUP BY ESTADO,BAIRRO
ORDER BY BAIRRO DESC;

USE SUCOS_VENDAS;

SELECT CODIGO_DO_PRODUTO, MAX(QUANTIDADE) AS QTDADE FROM itens_notas_fiscais
WHERE CODIGO_DO_PRODUTO = '1101035';

SELECT COUNT(*) FROM ITENS_NOTAS_FISCAIS
WHERE CODIGO_DO_PRODUTO = '1101035' AND QUANTIDADE = 99;
