USE VENDAS_SUCOS;

CREATE TABLE TAB_PADRAO(
ID INT AUTO_INCREMENT,
DESCRITOR VARCHAR(20),
ENDERECO VARCHAR(100) NULL /* NULL - é um padrão, se nada for informado será Nulo */,
CIDADE VARCHAR(50) DEFAULT 'Rio de Janeiro',
/* DEFAULT - padrão */
DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
/* TIMESTAMP - data e hora; CURRENT_TIMESTAMP - função que captura a data e hora do computador */
PRIMARY KEY (ID)
);

INSERT INTO TAB_PADRAO (DESCRITOR, ENDERECO, CIDADE, DATA_CRIACAO)
VALUES('CLIENTE X', 'RUA PROJETADA A', 'SÃO PAULO', '2019-01-01');

INSERT INTO TAB_PADRAO (DESCRITOR) VALUES ('CLIENTE Y');

SELECT * FROM TAB_PADRAO;