USE VENDAS_SUCOS;

SELECT * FROM VENDEDORES;

SELECT * FROM SUCOS_VENDAS.TABELA_DE_VENDEDORES;

/* Inicialmente olhar e comparar as duas tabelas em uma linha */
SELECT * FROM VENDEDORES A
INNER JOIN SUCOS_VENDAS.TABELA_DE_VENDEDORES B
ON A.MATRICULA = SUBSTRING(B.MATRICULA,3,3);

UPDATE VENDEDORES A INNER JOIN SUCOS_VENDAS.TABELA_DE_VENDEDORES B
ON A.MATRICULA = SUBSTRING(B.MATRICULA,3,3)
SET A.FERIAS = B.DE_FERIAS;

/* Após ajuste do campo férias */
SELECT * FROM VENDEDORES A
INNER JOIN SUCOS_VENDAS.TABELA_DE_VENDEDORES B
ON A.MATRICULA = SUBSTRING(B.MATRICULA,3,3);

SELECT * FROM VENDEDORES;
SELECT * FROM CLIENTES;

SELECT * FROM CLIENTES A 
INNER JOIN VENDEDORES B
ON A.BAIRRO = B.BAIRRO;

UPDATE CLIENTES A INNER JOIN VENDEDORES B
ON A.BAIRRO = B.BAIRRO
SET A.VOLUME_COMPRA = A.VOLUME_COMPRA * 1.30;